/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Signal", params := [], indices := [], level := 1, status := (.complete ["idle", "wake", "pair"]), constructors := [{ name := "idle", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "wake", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "pair", args := [(.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])])

def sampleType : Term :=
  (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated

namespace KanonMeta.MuFinitary.Control
example : Generated.declaration = { name := "Signal", params := [], indices := [], level := 1, status := .complete ["idle", "wake", "pair"], constructors := [{ name := "idle", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "wake", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "pair", args := [(.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }], positive := true } := rfl
example : (match validate Generated.declaration with
  | .ok (_checked) => true
  | .error (_error) => false) = true := rfl
example : Generated.sample = (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) := rfl
example : Generated.sampleType = (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])) := rfl
example : Generated.sampleRecArg = none := rfl
example : Generated.samplePartial = false := rfl
example : Generated.sampleReducible = true := rfl
end KanonMeta.MuFinitary.Control
