/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Orchard", params := [], indices := [], level := 1, status := (.complete ["seed", "stem", "branch", "canopy"]), constructors := [{ name := "seed", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "stem", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "branch", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "canopy", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])])

def sampleType : Term :=
  (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated

namespace KanonMeta.MuFinitary.Control
example : Generated.declaration = { name := "Orchard", params := [], indices := [], level := 1, status := .complete ["seed", "stem", "branch", "canopy"], constructors := [{ name := "seed", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "stem", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "branch", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "canopy", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true } := rfl
example : (match validate Generated.declaration with
  | .ok (_checked) => true
  | .error (_error) => false) = true := rfl
example : Generated.sample = (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) := rfl
example : Generated.sampleType = (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])) := rfl
example : Generated.sampleRecArg = none := rfl
example : Generated.samplePartial = false := rfl
example : Generated.sampleReducible = true := rfl
end KanonMeta.MuFinitary.Control
