/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Grove", params := [], indices := [], level := 1, status := (.complete ["bud", "shoot", "join", "crown"]), constructors := [{ name := "bud", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "shoot", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "join", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "crown", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])])])

def sampleType : Term :=
  (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated
