/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuNat

namespace KanonMeta.MuNat.Generated

def declaration : Declaration :=
  { name := "N", params := [], indices := [], level := 1, status := (.complete ["zero", "succ"]), constructors := [{ name := "zero", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "succ", args := [(.many, "_", (.lan (.SMu "N" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }], positive := true }

def three : Term :=
  (.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "zero") [])])])])

def threeType : Term :=
  (.lan (.SMu "N" []) (.sec (.SColl 0) []))

def threeRecArg : Option Nat := none
def threePartial : Bool := false
def threeReducible : Bool := true

def double : Term :=
  (.sec (.SPi .many "n" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) [(.mk [(.many, "n")] (.elim (.SMu "N" []) (.var 0) .one (some (.mk (some "N") [] "x" (.lan (.SMu "N" []) (.sec (.SColl 0) [])))) [((.actor "zero"), (.mk [] (.intro (.SMu "N" []) (.actor "zero") []))), ((.actor "succ"), (.mk [(.many, "m")] (.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "succ") [(.out (.SPi .many "_" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) (.apt .many (.var 0)) (.global "double"))])])))]))])

def doubleType : Term :=
  (.ran (.SPi .many "_" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) (.lan (.SMu "N" []) (.sec (.SColl 0) [])))

def doubleRecArg : Option Nat := (some 0)
def doublePartial : Bool := false
def doubleReducible : Bool := true

end KanonMeta.MuNat.Generated
