/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuTree

namespace KanonMeta.MuTree.Generated

def declaration : MuNat.Declaration :=
  { name := "Tree", params := [], indices := [], level := 1, status := (.complete ["leaf", "fork"]), constructors := [{ name := "leaf", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "fork", args := [(.many, "_", (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Tree" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Tree" []) (.actor "fork") [(.intro (.SMu "Tree" []) (.actor "leaf") []), (.intro (.SMu "Tree" []) (.actor "fork") [(.intro (.SMu "Tree" []) (.actor "leaf") []), (.intro (.SMu "Tree" []) (.actor "leaf") [])])])

def sampleType : Term :=
  (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

def mirror : Term :=
  (.sec (.SPi .many "t" (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))) [(.mk [(.many, "t")] (.elim (.SMu "Tree" []) (.var 0) .one (some (.mk (some "Tree") [] "x" (.lan (.SMu "Tree" []) (.sec (.SColl 0) [])))) [((.actor "leaf"), (.mk [] (.intro (.SMu "Tree" []) (.actor "leaf") []))), ((.actor "fork"), (.mk [(.many, "l"), (.many, "r")] (.intro (.SMu "Tree" []) (.actor "fork") [(.out (.SPi .many "_" (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))) (.apt .many (.var 0)) (.global "mirror")), (.out (.SPi .many "_" (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))) (.apt .many (.var 1)) (.global "mirror"))])))]))])

def mirrorType : Term :=
  (.ran (.SPi .many "_" (.lan (.SMu "Tree" []) (.sec (.SColl 0) []))) (.lan (.SMu "Tree" []) (.sec (.SColl 0) [])))

def mirrorRecArg : Option Nat := (some 0)
def mirrorPartial : Bool := false
def mirrorReducible : Bool := true

end KanonMeta.MuTree.Generated
