/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuVector

namespace KanonMeta.MuVector.Generated

def naturalDeclaration : MuNat.Declaration :=
  { name := "N", params := [], indices := [], level := 1, status := (.complete ["zero", "succ"]), constructors := [{ name := "zero", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "succ", args := [(.many, "_", (.lan (.SMu "N" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }], positive := true }

def declaration : MuNat.Declaration :=
  { name := "V", params := [], indices := [(.zero, "i", (.lan (.SMu "N" []) (.sec (.SColl 0) [])))], level := 1, status := (.complete ["vz", "vs"]), constructors := [{ name := "vz", args := [], resultIndices := [(.intro (.SMu "N" []) (.actor "zero") [])], fullArity := 0, selfRecursive := false }, { name := "vs", args := [(.zero, "i", (.lan (.SMu "N" []) (.sec (.SColl 0) []))), (.many, "_", (.global "Nat")), (.many, "_", (.lan (.SMu "V" [(.var 1)]) (.sec (.SColl 0) [])))], resultIndices := [(.intro (.SMu "N" []) (.actor "succ") [(.var 2)])], fullArity := 3, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "V" [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "zero") [])])])]) (.actor "vs") [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "zero") [])]), (.lit 17), (.intro (.SMu "V" [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "zero") [])])]) (.actor "vs") [(.intro (.SMu "N" []) (.actor "zero") []), (.lit 25), (.intro (.SMu "V" [(.intro (.SMu "N" []) (.actor "zero") [])]) (.actor "vz") [])])])

def sampleType : Term :=
  (.lan (.SMu "V" [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "succ") [(.intro (.SMu "N" []) (.actor "zero") [])])])]) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

def copy : Term :=
  (.sec (.SPi .zero "i" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) [(.mk [(.zero, "i")] (.sec (.SPi .many "v" (.lan (.SMu "V" [(.var 0)]) (.sec (.SColl 0) []))) [(.mk [(.many, "v")] (.elim (.SMu "V" [(.var 1)]) (.var 0) .one (some (.mk (some "V") ["j"] "x" (.lan (.SMu "V" [(.var 1)]) (.sec (.SColl 0) [])))) [((.actor "vz"), (.mk [] (.intro (.SMu "V" [(.intro (.SMu "N" []) (.actor "zero") [])]) (.actor "vz") []))), ((.actor "vs"), (.mk [(.zero, "j"), (.many, "a"), (.many, "w")] (.intro (.SMu "V" [(.intro (.SMu "N" []) (.actor "succ") [(.var 2)])]) (.actor "vs") [(.var 2), (.var 1), (.out (.SPi .many "_" (.lan (.SMu "V" [(.var 2)]) (.sec (.SColl 0) []))) (.apt .many (.var 0)) (.out (.SPi .zero "i" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) (.apt .zero (.var 2)) (.global "copy")))])))]))]))])

def copyType : Term :=
  (.ran (.SPi .zero "i" (.lan (.SMu "N" []) (.sec (.SColl 0) []))) (.ran (.SPi .many "_" (.lan (.SMu "V" [(.var 0)]) (.sec (.SColl 0) []))) (.lan (.SMu "V" [(.var 1)]) (.sec (.SColl 0) []))))

def copyRecArg : Option Nat := (some 1)
def copyPartial : Bool := false
def copyReducible : Bool := true

end KanonMeta.MuVector.Generated
