import KanonMeta.MuFinitaryDecode
/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Signal", params := [], indices := [], level := 1, status := (.complete ["idle", "wake", "pair"]), constructors := [{ name := "idle", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "wake", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "pair", args := [(.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])])

def sampleType : Term :=
  (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated

namespace KanonMeta.MuFinitary.Control
example : Generated.declaration = { name := "Signal", params := [], indices := [], level := 1, status := .complete ["idle", "wake", "pair"], constructors := [{ name := "idle", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "wake", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "pair", args := [(.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }], positive := true } := rfl
example : (match validate Generated.declaration with
  | .ok (_checked) => true
  | .error (_error) => false) = true := rfl
example : Generated.sample = (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) := rfl
example : Generated.sampleType = (.lan (.SMu "Signal" []) (.sec (.SColl 0) [])) := rfl
example : Generated.sampleRecArg = none := rfl
example : Generated.samplePartial = false := rfl
example : Generated.sampleReducible = true := rfl

def expectedSpec : Spec := ⟨"Signal", [⟨"idle", []⟩, ⟨"wake", []⟩, ⟨"pair", ["_", "_"]⟩]⟩
example : Generated.declaration = expectedSpec.declaration := rfl
example : expectedSpec.Valid := of_decide_eq_true rfl

def decodedEncoding (term : Term) : Except DecodeError Term :=
  match decode expectedSpec term with
  | .ok decoded => .ok decoded.value.encode
  | .error error => .error error

def decodedObservation (term : Term) : Except DecodeError Nat :=
  match decode expectedSpec term with
  | .ok decoded => .ok (decoded.value.fold (fun ctor children =>
      (List.ofFn children).foldl (fun total child => 11 * total + child) (ctor.val + 1)))
  | .error error => .error error

example : decodedEncoding Generated.sample = .ok (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) := rfl
example : decodedObservation Generated.sample = .ok 376 := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "wake") []), (.intro (.SMu "Signal" []) (.actor "idle") [])]) = .ok (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "wake") []), (.intro (.SMu "Signal" []) (.actor "idle") [])]) := rfl
example : decodedObservation (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "wake") []), (.intro (.SMu "Signal" []) (.actor "idle") [])]) = .ok 386 := rfl
example : decodedObservation Generated.sample ≠ decodedObservation (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "wake") []), (.intro (.SMu "Signal" []) (.actor "idle") [])]) :=
  fun equal => (show (376 : Nat) ≠ 386 from of_decide_eq_true rfl)
    (Except.ok.inj equal)
example : decodedEncoding (.intro (.SColl 0) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.wrongShape) := rfl
example : decodedEncoding (.intro (.SMu "AbsentFamily" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.wrongFamily "AbsentFamily") := rfl
example : decodedEncoding (.intro (.SMu "Signal" [.lit 0]) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.indexedFamily 1) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.aleg 0) [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.apt .many (.lit 0)) [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "absentConstructor") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.wrongAddress "absentConstructor") := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") [])]) = .error (.wrongArity "pair" 2 1) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.intro (.SMu "Signal" []) (.actor "wake") []), (.lit 0)]) = .error (.wrongArity "pair" 2 3) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "pair") [(.var 0), (.intro (.SMu "Signal" []) (.actor "wake") [])]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.intro (.SMu "Signal" []) (.actor "pair") [(.intro (.SMu "Signal" []) (.actor "idle") []), (.var 0)]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.var 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.univ 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lan (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ran (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.elim (.SColl 0) (.lit 0) .many none []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.sec (.SColl 0) []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.out (.SColl 0) (.aleg 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.letIn "x" (.univ 0) (.lit 0) (.var 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ann (.lit 0) (.univ 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.global "sample") = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lit 0) = .error (.unsupportedTerm) := rfl

end KanonMeta.MuFinitary.Control
