import KanonMeta.MuFinitaryDecode
/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Orchard", params := [], indices := [], level := 1, status := (.complete ["seed", "stem", "branch", "canopy"]), constructors := [{ name := "seed", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "stem", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "branch", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "canopy", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])])

def sampleType : Term :=
  (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated

namespace KanonMeta.MuFinitary.Control
example : Generated.declaration = { name := "Orchard", params := [], indices := [], level := 1, status := .complete ["seed", "stem", "branch", "canopy"], constructors := [{ name := "seed", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "stem", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "branch", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "canopy", args := [(.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true } := rfl
example : (match validate Generated.declaration with
  | .ok (_checked) => true
  | .error (_error) => false) = true := rfl
example : Generated.sample = (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) := rfl
example : Generated.sampleType = (.lan (.SMu "Orchard" []) (.sec (.SColl 0) [])) := rfl
example : Generated.sampleRecArg = none := rfl
example : Generated.samplePartial = false := rfl
example : Generated.sampleReducible = true := rfl

def expectedSpec : Spec := ⟨"Orchard", [⟨"seed", []⟩, ⟨"stem", ["_"]⟩, ⟨"branch", ["_", "_"]⟩, ⟨"canopy", ["_", "_", "_"]⟩]⟩
example : Generated.declaration = expectedSpec.declaration := rfl
example : expectedSpec.Valid := of_decide_eq_true rfl

def decodedEncoding (term : Term) : Except DecodeError Term :=
  match decode expectedSpec term with
  | .ok decoded => .ok decoded.value.encode
  | .error error => .error error

def decodedObservation (term : Term) : Except DecodeError Nat :=
  match decode expectedSpec term with
  | .ok decoded => .ok (decoded.value.fold (fun ctor children =>
      (List.ofFn children).foldl (fun total child => 11 * total + child) (ctor.val + 1)))
  | .error error => .error error

example : decodedEncoding Generated.sample = .ok (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) := rfl
example : decodedObservation Generated.sample = .ok 6095 := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "seed") [])]) = .ok (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "seed") [])]) := rfl
example : decodedObservation (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "seed") [])]) = .ok 53615 := rfl
example : decodedObservation Generated.sample ≠ decodedObservation (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "seed") [])]) :=
  fun equal => (show (6095 : Nat) ≠ 53615 from of_decide_eq_true rfl)
    (Except.ok.inj equal)
example : decodedEncoding (.intro (.SColl 0) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.wrongShape) := rfl
example : decodedEncoding (.intro (.SMu "AbsentFamily" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.wrongFamily "AbsentFamily") := rfl
example : decodedEncoding (.intro (.SMu "Orchard" [.lit 0]) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.indexedFamily 1) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.aleg 0) [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.apt .many (.lit 0)) [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "absentConstructor") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.wrongAddress "absentConstructor") := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]) = .error (.wrongArity "canopy" 3 2) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])]), (.lit 0)]) = .error (.wrongArity "canopy" 3 4) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.var 0), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.var 0), (.intro (.SMu "Orchard" []) (.actor "branch") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])])])]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.intro (.SMu "Orchard" []) (.actor "canopy") [(.intro (.SMu "Orchard" []) (.actor "seed") []), (.intro (.SMu "Orchard" []) (.actor "stem") [(.intro (.SMu "Orchard" []) (.actor "seed") [])]), (.var 0)]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.var 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.univ 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lan (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ran (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.elim (.SColl 0) (.lit 0) .many none []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.sec (.SColl 0) []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.out (.SColl 0) (.aleg 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.letIn "x" (.univ 0) (.lit 0) (.var 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ann (.lit 0) (.univ 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.global "sample") = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lit 0) = .error (.unsupportedTerm) := rfl

end KanonMeta.MuFinitary.Control
