import KanonMeta.MuFinitaryDecode
/- Generated by dev/mu-bridge/export_mu.ml from the checked fixture. -/
import KanonMeta.MuFinitary

namespace KanonMeta.MuFinitary.Generated

def declaration : MuNat.Declaration :=
  { name := "Grove", params := [], indices := [], level := 1, status := (.complete ["bud", "shoot", "join", "crown"]), constructors := [{ name := "bud", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "shoot", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "join", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "crown", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true }

def sample : Term :=
  (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])])

def sampleType : Term :=
  (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))

def sampleRecArg : Option Nat := none
def samplePartial : Bool := false
def sampleReducible : Bool := true

end KanonMeta.MuFinitary.Generated

namespace KanonMeta.MuFinitary.Control
example : Generated.declaration = { name := "Grove", params := [], indices := [], level := 1, status := .complete ["bud", "shoot", "join", "crown"], constructors := [{ name := "bud", args := [], resultIndices := [], fullArity := 0, selfRecursive := false }, { name := "shoot", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 1, selfRecursive := true }, { name := "join", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 2, selfRecursive := true }, { name := "crown", args := [(.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) []))), (.many, "_", (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])))], resultIndices := [], fullArity := 3, selfRecursive := true }], positive := true } := rfl
example : (match validate Generated.declaration with
  | .ok (_checked) => true
  | .error (_error) => false) = true := rfl
example : Generated.sample = (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) := rfl
example : Generated.sampleType = (.lan (.SMu "Grove" []) (.sec (.SColl 0) [])) := rfl
example : Generated.sampleRecArg = none := rfl
example : Generated.samplePartial = false := rfl
example : Generated.sampleReducible = true := rfl

def expectedSpec : Spec := ⟨"Grove", [⟨"bud", []⟩, ⟨"shoot", ["_"]⟩, ⟨"join", ["_", "_"]⟩, ⟨"crown", ["_", "_", "_"]⟩]⟩
example : Generated.declaration = expectedSpec.declaration := rfl
example : expectedSpec.Valid := of_decide_eq_true rfl

def decodedEncoding (term : Term) : Except DecodeError Term :=
  match decode expectedSpec term with
  | .ok decoded => .ok decoded.value.encode
  | .error error => .error error

def decodedObservation (term : Term) : Except DecodeError Nat :=
  match decode expectedSpec term with
  | .ok decoded => .ok (decoded.value.fold (fun ctor children =>
      (List.ofFn children).foldl (fun total child => 11 * total + child) (ctor.val + 1)))
  | .error error => .error error

example : decodedEncoding Generated.sample = .ok (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) := rfl
example : decodedObservation Generated.sample = .ok 9835 := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "bud") [])]) = .ok (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "bud") [])]) := rfl
example : decodedObservation (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "bud") [])]) = .ok 12475 := rfl
example : decodedObservation Generated.sample ≠ decodedObservation (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "bud") [])]) :=
  fun equal => (show (9835 : Nat) ≠ 12475 from of_decide_eq_true rfl)
    (Except.ok.inj equal)
example : decodedEncoding (.intro (.SColl 0) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.wrongShape) := rfl
example : decodedEncoding (.intro (.SMu "AbsentFamily" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.wrongFamily "AbsentFamily") := rfl
example : decodedEncoding (.intro (.SMu "Grove" [.lit 0]) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.indexedFamily 1) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.aleg 0) [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.apt .many (.lit 0)) [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.nonConstructorAddress) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "absentConstructor") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.wrongAddress "absentConstructor") := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])])]) = .error (.wrongArity "crown" 3 2) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])]), (.lit 0)]) = .error (.wrongArity "crown" 3 4) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.var 0), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.var 0), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.intro (.SMu "Grove" []) (.actor "crown") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "join") [(.intro (.SMu "Grove" []) (.actor "bud") []), (.intro (.SMu "Grove" []) (.actor "shoot") [(.intro (.SMu "Grove" []) (.actor "bud") [])])]), (.var 0)]) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.var 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.univ 0) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lan (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ran (.SColl 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.elim (.SColl 0) (.lit 0) .many none []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.sec (.SColl 0) []) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.out (.SColl 0) (.aleg 0) (.lit 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.letIn "x" (.univ 0) (.lit 0) (.var 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.ann (.lit 0) (.univ 0)) = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.global "sample") = .error (.unsupportedTerm) := rfl
example : decodedEncoding (.lit 0) = .error (.unsupportedTerm) := rfl

end KanonMeta.MuFinitary.Control
